/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { Ollama, type Message } from 'ollama';
import { FinishReason } from '@google/genai';
import type { GenerateContentResponse, Content } from '@google/genai';

/**
 * Utility functions for Ollama provider interactions
 */

/**
 * Recursively parses XML-style tool calls generated by local models inside text blocks.
 */
function parseXmlToolCalls(
  text: string,
): { name: string; args: Record<string, any> }[] {
  if (!text) return [];
  const toolCalls: { name: string; args: Record<string, any> }[] = [];

  // Regex to match <function=NAME>...</function>
  const functionRegex = /<function=([a-zA-Z0-9_-]+)>([\s\S]*?)<\/function>/g;
  let match;

  while ((match = functionRegex.exec(text)) !== null) {
    const name = match[1];
    const body = match[2];
    const args: Record<string, any> = {};

    // Regex to match <parameter=NAME>VALUE</parameter>
    const parameterRegex =
      /<parameter=([a-zA-Z0-9_-]+)>([\s\S]*?)<\/parameter>/g;
    let paramMatch;

    while ((paramMatch = parameterRegex.exec(body)) !== null) {
      const paramName = paramMatch[1];
      const paramValue = paramMatch[2].trim();
      args[paramName] = paramValue;
    }

    toolCalls.push({ name, args });
  }

  return toolCalls;
}

/**
 * Parse an Ollama response into the standard GenerateContentResponse format
 * @param response Ollama API response
 * @returns Standardized GenerateContentResponse
 */
export function parseOllamaResponse(response: any): GenerateContentResponse {
  const parts: any[] = [];
  const content = response.message?.content || '';

  // 1. Try to extract any structured tool calls from response.message.tool_calls
  let hasTools = false;
  if (response.message?.tool_calls && response.message.tool_calls.length > 0) {
    hasTools = true;
    for (const tc of response.message.tool_calls) {
      const args = tc.function.arguments || {};
      if (
        (tc.function.name === 'read_file' ||
          tc.function.name === 'write_file') &&
        args.path &&
        !args.file_path
      ) {
        args.file_path = args.path;
      }

      parts.push({
        functionCall: {
          id: tc.id || `call_${Math.random().toString(36).substring(2, 9)}`,
          name: tc.function.name,
          args,
        },
      });
    }
  }

  // 2. Also try to parse any XML-style tool calls embedded in the raw text content!
  const xmlCalls = parseXmlToolCalls(content);
  if (xmlCalls.length > 0) {
    hasTools = true;
    for (const call of xmlCalls) {
      parts.push({
        functionCall: {
          id: `call_${Math.random().toString(36).substring(2, 9)}`,
          name: call.name,
          args: call.args,
        },
      });
    }
  }

  // 3. If there are NO tool calls (neither structured nor XML), we push the standard text content.
  // Otherwise, we omit the text content to let the tool execution run cleanly.
  if (!hasTools && content) {
    parts.push({ text: content });
  }

  const functionCalls: any[] = [];
  for (const part of parts) {
    if (part.functionCall) {
      functionCalls.push(part.functionCall);
    }
  }

  return {
    candidates: [
      {
        content: {
          role: 'model',
          parts,
        },
        finishReason: FinishReason.STOP,
      },
    ],
    functionCalls: functionCalls.length > 0 ? functionCalls : undefined,
    usageMetadata: {
      promptTokenCount: response.prompt_eval_count,
      candidatesTokenCount: response.eval_count,
      totalTokenCount:
        (response.prompt_eval_count || 0) + (response.eval_count || 0),
    },
  } as GenerateContentResponse;
}

/**
 * Handle Ollama API errors with standardized error messages
 * @param error The error object from Ollama API call
 * @param model The model name that was being used
 * @returns User-friendly error message
 */
export function handleOllamaError(error: any, model: string): string {
  if (!error) {
    return `An unknown error occurred while calling Ollama model ${model}.`;
  }

  // Check if it's a known Ollama error format
  if (error.response) {
    const status = error.response.status;
    const message = error.response.data?.error || error.response.statusText;

    switch (status) {
      case 400:
        return `Bad request to Ollama API for model ${model}: ${message}`;
      case 404:
        return `Model ${model} not found. Please ensure it's pulled using 'ollama pull ${model}'.`;
      case 429:
        return `Rate limit exceeded for Ollama model ${model}. Please try again later.`;
      case 500:
        return `Internal server error in Ollama for model ${model}: ${message}`;
      default:
        return `Ollama API error (${status}) for model ${model}: ${message}`;
    }
  }

  // Check if it's an Ollama-specific error object
  if (error.error) {
    return `Ollama error for model ${model}: ${error.error}`;
  }

  // Generic error handling
  return `Unexpected error while calling Ollama model ${model}: ${error.message || 'Unknown error'}`;
}

const validatedModels = new Set<string>();

/**
 * Validate that a model is available in Ollama
 * @param model The model name to validate
 * @param host Optional Ollama host URL
 * @returns Promise that resolves if model is valid, rejects with error otherwise
 */
export async function validateOllamaModel(
  model: string,
  host?: string,
): Promise<void> {
  const cacheKey = `${host || ''}:${model}`;
  if (validatedModels.has(cacheKey)) {
    return;
  }

  try {
    const client = new Ollama({
      host: host || process.env['OLLAMA_HOST'] || 'http://localhost:11434',
    });

    // Try to get model info to validate it exists
    await client.show({ model });
    validatedModels.add(cacheKey);
    return;
  } catch (error: any) {
    // Handle specific error cases
    if (error.response && error.response.status === 404) {
      throw new Error(
        `Model ${model} not found. Please ensure it's pulled using 'ollama pull ${model}'.`,
      );
    }

    // Re-throw with standardized message
    throw new Error(handleOllamaError(error, model));
  }
}

/**
 * Convert Gemini Content arrays to Ollama Message format
 * @param contents Array of Gemini Content objects
 * @param systemInstruction Optional system instruction
 * @returns Array of Ollama Message objects
 */
export function convertToOllamaMessages(
  contents: Content[],
  systemInstruction?: string | any | any[] | Content,
): Message[] {
  const messages: Message[] = [];

  if (systemInstruction) {
    let systemText = '';
    if (typeof systemInstruction === 'string') {
      systemText = systemInstruction;
    } else if (Array.isArray(systemInstruction)) {
      systemText = systemInstruction
        .map((p) => (p as any).text || '')
        .join('\n');
    } else if (
      systemInstruction &&
      'parts' in systemInstruction &&
      systemInstruction.parts
    ) {
      systemText = (systemInstruction.parts as any[])
        .map((p) => p.text || '')
        .join('\n');
    } else {
      systemText = (systemInstruction as any).text || '';
    }

    if (systemText) {
      messages.push({ role: 'system', content: systemText });
    }
  }

  for (const content of contents) {
    const role = content.role === 'model' ? 'assistant' : 'user';
    const parts = content.parts || [];

    let textContent = '';
    const toolCalls: any[] = [];

    for (const part of parts) {
      if (part.text) {
        textContent += part.text;
      }
      if (part.functionCall) {
        toolCalls.push({
          id:
            part.functionCall.id ||
            `call_${Math.random().toString(36).substring(2, 9)}`,
          type: 'function',
          function: {
            name: part.functionCall.name,
            arguments: part.functionCall.args,
          },
        });
      }
      if (part.functionResponse) {
        messages.push({
          role: 'tool',
          content: JSON.stringify(part.functionResponse.response),
          name: part.functionResponse.name,
          tool_call_id: part.functionResponse.id,
        } as any);
      }
    }

    if (textContent || toolCalls.length > 0) {
      messages.push({
        role,
        content: textContent,
        tool_calls: toolCalls.length > 0 ? toolCalls : undefined,
      });
    }
  }

  return messages;
}

/**
 * Recursively converts uppercase types in a JSON Schema to lowercase as required by Ollama.
 */
export function convertSchemaTypesToLowercase(schema: any): any {
  if (!schema || typeof schema !== 'object') return schema;

  if (Array.isArray(schema)) {
    return schema.map(convertSchemaTypesToLowercase);
  }

  const result: any = {};
  for (const [key, value] of Object.entries(schema)) {
    if (key === 'type' && typeof value === 'string') {
      result[key] = value.toLowerCase();
    } else if (typeof value === 'object') {
      result[key] = convertSchemaTypesToLowercase(value);
    } else {
      result[key] = value;
    }
  }
  return result;
}

/**
 * Convert tool definitions to Ollama-compatible format
 * @param tools Array of tool definitions
 * @returns Ollama-compatible tools array
 */
export function convertToolsToOllamaFormat(tools?: any[]): any[] | undefined {
  if (!tools || tools.length === 0) return undefined;

  const ollamaTools: any[] = [];
  for (const tool of tools) {
    if (tool.functionDeclarations) {
      for (const fd of tool.functionDeclarations) {
        ollamaTools.push({
          type: 'function',
          function: {
            name: fd.name,
            description: fd.description,
            parameters: convertSchemaTypesToLowercase(fd.parameters) as any,
          },
        });
      }
    }
  }
  return ollamaTools.length > 0 ? ollamaTools : undefined;
}
